// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "InstancedActorsComponent.h"
#include "UObject/Interface.h"
#include "ExampleInstancedActorComponent.generated.h"

class UStaticMesh;

UINTERFACE(MinimalAPI, Blueprintable)
class UExampleVisualStateRestorable : public UInterface
{
	GENERATED_BODY()
};

class PERSISTENCEEXAMPLES_API IExampleVisualStateRestorable
{
	GENERATED_BODY()

public:
	// Called by UExampleInstancedActorComponent::InitializeComponentForInstance to restore the actor's
	// visual state from its Mass entity. Implementers should set whatever local state mirrors VisualStateIndex.
	UFUNCTION(BlueprintNativeEvent, BlueprintCallable, Category = "InstancedActors")
	void OnVisualStateRestored(int32 VisualStateIndex);
	virtual void OnVisualStateRestored_Implementation(int32 VisualStateIndex) {}
};

UENUM()
enum class EVisualDescriptionGenerationType : uint8
{
	// Visual state 0 is generated by the engine from the exemplar's StaticMeshComponents.
	// No additional states are registered. AdditionalVisualStates is ignored.
	Default,

	// Visual state 0 is still generated by the engine from StaticMeshComponents.
	// Visual states 1..N are registered from AdditionalVisualStates[0..N-1] (i.e. AdditionalVisualStates[K]
	// configures visual state K+1).
	PropertyConfigured,
};

UENUM()
enum class EVisualStateTransformModification : uint8
{
	// Keep the descriptor's existing LocalTransform (the value FromActor captured from the SMC).
	None,
	// Replace LocalTransform with TransformToApply.
	Override,
	// Set LocalTransform = TransformToApply * existing LocalTransform.
	ApplyRelative,
};

USTRUCT(BlueprintType)
struct FVisualStateMeshOverride
{
	GENERATED_BODY()

	// If false, the SMC is hidden at this visual state. On the IA path the descriptor is omitted from
	// the visualization (so no ISM instance is placed); on the hydrated actor the SMC's visibility flag
	// is cleared. true = visible (matches no-override / state 0 behavior).
	UPROPERTY(EditAnywhere, Category = "InstancedActors")
	bool bVisible = true;

	// Optional. If non-null, replaces the descriptor's StaticMesh. Null = keep existing mesh.
	UPROPERTY(EditAnywhere, Category = "InstancedActors", meta = (EditCondition = "bVisible"))
	TObjectPtr<UStaticMesh> StaticMeshOverride = nullptr;

	UPROPERTY(EditAnywhere, Category = "InstancedActors", meta = (EditCondition = "bVisible"))
	EVisualStateTransformModification TransformModification = EVisualStateTransformModification::None;

	UPROPERTY(EditAnywhere, Category = "InstancedActors", meta = (EditCondition = "bVisible && TransformModification != EVisualStateTransformModification::None"))
	FTransform TransformToApply = FTransform::Identity;
};

USTRUCT(BlueprintType)
struct FVisualStateSMCOverrides
{
	GENERATED_BODY()

	// Keyed by source StaticMeshComponent FName (as it appears on the exemplar / hydrated actor).
	// SMCs whose name isn't in the map are left untouched at this visual state.
	UPROPERTY(EditAnywhere, Category = "InstancedActors")
	TMap<FName, FVisualStateMeshOverride> Overrides;
};

/**
 * Reusable instanced-actor component for the PersistenceLab demos. Supports:
 *  - Data-driven multi-state visualization (mesh + relative transform per mesh, multiple meshes per state).
 *  - Optional GAS health sync: pushes FHealthFragment <-> UHealthAttributeSet on hydrate / EndPlay.
 *  - Sparse persistence of viz/health deltas vs. the IAD defaults.
 *
 * The owning actor must implement IAbilitySystemInterface and own a UHealthAttributeSet
 * when bSupportsHealth is true.
 */
UCLASS(ClassGroup = "Instanced Actors", Meta = (BlueprintSpawnableComponent))
class PERSISTENCEEXAMPLES_API UExampleInstancedActorComponent : public UInstancedActorsComponent
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, Category = "InstancedActors|Visualization")
	EVisualDescriptionGenerationType VisualDescriptionGenerationType = EVisualDescriptionGenerationType::Default;

	// Configures visual states 1..N (state 0 is engine-built from the exemplar's StaticMeshComponents via
	// FromActor and needs no entry). AdditionalVisualStates[K] configures visual state K+1 — derived in
	// ModifyMassEntityTemplate by copying state 0's descriptors and applying the per-SMC-name overrides here.
	UPROPERTY(EditAnywhere, Category = "InstancedActors|Visualization",
		meta = (EditCondition = "VisualDescriptionGenerationType == EVisualDescriptionGenerationType::PropertyConfigured"))
	TArray<FVisualStateSMCOverrides> AdditionalVisualStates;

	UPROPERTY(EditAnywhere, Category = "InstancedActors|Health")
	bool bSupportsHealth = false;

	// UInstancedActorsComponent
	virtual void ModifyMassEntityConfig(FMassEntityManager& InMassEntityManager, UInstancedActorsData* InstancedActorData, FMassEntityConfig& InOutMassEntityConfig) const override;
	virtual void ModifyMassEntityTemplate(FMassEntityManager& InMassEntityManager, UInstancedActorsData* InstancedActorData, FMassEntityTemplateData& InOutMassEntityTemplateData) const override;
	virtual void InitializeComponentForInstance(FInstancedActorsInstanceHandle InInstanceHandle) override;
	virtual uint32 GetInstancePersistenceDataID() const override;
	virtual bool ShouldSerializeInstancePersistenceData(const FArchive& Archive, UInstancedActorsData* InstanceData, int64 TimeDelta) const override;
	virtual void SerializeInstancePersistenceData(FStructuredArchive::FRecord Record, UInstancedActorsData* InstanceData, int64 TimeDelta) const override;

	// UActorComponent
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	// Switch this instance's visual state. Updates both server and (with the client workaround) client.
	UFUNCTION(BlueprintCallable, Category = "InstancedActors")
	void NotifyVisualStateChanged(int32 NewVisualState);

	// Push the current health/max-health into the entity's FHealthFragment immediately (in addition to
	// the EndPlay flush). Call this when health changes are infrequent or you want save-time accuracy.
	UFUNCTION(BlueprintCallable, Category = "InstancedActors|Health")
	void NotifyHealthChanged(float NewHealth, float NewMaxHealth);

	// Marks this instance as destroyed in the IAD delta list. The actor + entity are released next tick.
	UFUNCTION(BlueprintCallable, Category = "InstancedActors")
	void DestroyInstance();

	// Unlinks the actor from Mass and marks the instance as destroyed (so the IAM won't respawn it),
	// but leaves the actor alive in the world to persist itself. Use this when an instance transitions
	// from managed to free — e.g., a crate that fractures and needs Chaos to take over the pieces.
	UFUNCTION(BlueprintCallable, Category = "InstancedActors")
	void EjectInstance();

	FDelegateHandle PreIAMFlushHandle;
};
